//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace AltInnSrr.Connected_Services.AltInnSrrService
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [DataContract(Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
    public partial class AltinnFault : object
    {
        
        private string AltinnErrorMessageField;
        
        private string AltinnExtendedErrorMessageField;
        
        private string AltinnLocalizedErrorMessageField;
        
        private string ErrorGuidField;
        
        private int ErrorIDField;
        
        private string UserGuidField;
        
        private string UserIdField;
        
        [DataMember()]
        public string AltinnErrorMessage
        {
            get
            {
                return this.AltinnErrorMessageField;
            }
            set
            {
                this.AltinnErrorMessageField = value;
            }
        }
        
        [DataMember()]
        public string AltinnExtendedErrorMessage
        {
            get
            {
                return this.AltinnExtendedErrorMessageField;
            }
            set
            {
                this.AltinnExtendedErrorMessageField = value;
            }
        }
        
        [DataMember()]
        public string AltinnLocalizedErrorMessage
        {
            get
            {
                return this.AltinnLocalizedErrorMessageField;
            }
            set
            {
                this.AltinnLocalizedErrorMessageField = value;
            }
        }
        
        [DataMember()]
        public string ErrorGuid
        {
            get
            {
                return this.ErrorGuidField;
            }
            set
            {
                this.ErrorGuidField = value;
            }
        }
        
        [DataMember()]
        public int ErrorID
        {
            get
            {
                return this.ErrorIDField;
            }
            set
            {
                this.ErrorIDField = value;
            }
        }
        
        [DataMember()]
        public string UserGuid
        {
            get
            {
                return this.UserGuidField;
            }
            set
            {
                this.UserGuidField = value;
            }
        }
        
        [DataMember()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [CollectionDataContract(Name="GetRightResponseList", Namespace="http://schemas.altinn.no/services/Register/SRR/2015/06", ItemName="GetRightResponse")]
    public class GetRightResponseList : System.Collections.Generic.List<AltInnSrrService.GetRightResponse>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [DataContract(Name="GetRightResponse", Namespace="http://schemas.altinn.no/services/Register/SRR/2015/06")]
    public partial class GetRightResponse : AltInnSrrService.RegisterSRRRight
    {
        
        private System.DateTime ValidToField;
        
        [DataMember()]
        public System.DateTime ValidTo
        {
            get
            {
                return this.ValidToField;
            }
            set
            {
                this.ValidToField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [DataContract(Name="RegisterSRRRight", Namespace="http://schemas.altinn.no/services/Register/SRR/2015/06")]
    [KnownType(typeof(AltInnSrrService.AddRightRequest))]
    [KnownType(typeof(AltInnSrrService.AddRightResponse))]
    [KnownType(typeof(AltInnSrrService.DeleteRightRequest))]
    [KnownType(typeof(AltInnSrrService.DeleteRightResponse))]
    [KnownType(typeof(AltInnSrrService.GetRightResponse))]
    public partial class RegisterSRRRight : object
    {
        
        private string ConditionField;
        
        private string ReporteeField;
        
        private AltInnSrrService.RegisterSRRRightsType RightField;
        
        [DataMember()]
        public string Condition
        {
            get
            {
                return this.ConditionField;
            }
            set
            {
                this.ConditionField = value;
            }
        }
        
        [DataMember(IsRequired=true)]
        public string Reportee
        {
            get
            {
                return this.ReporteeField;
            }
            set
            {
                this.ReporteeField = value;
            }
        }
        
        [DataMember(IsRequired=true)]
        public AltInnSrrService.RegisterSRRRightsType Right
        {
            get
            {
                return this.RightField;
            }
            set
            {
                this.RightField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [DataContract(Name="AddRightRequest", Namespace="http://schemas.altinn.no/services/Register/SRR/2015/06")]
    [KnownType(typeof(AltInnSrrService.AddRightResponse))]
    public partial class AddRightRequest : AltInnSrrService.RegisterSRRRight
    {
        
        private System.DateTime ValidToField;
        
        [DataMember(IsRequired=true)]
        public System.DateTime ValidTo
        {
            get
            {
                return this.ValidToField;
            }
            set
            {
                this.ValidToField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [DataContract(Name="AddRightResponse", Namespace="http://schemas.altinn.no/services/Register/SRR/2015/06")]
    public partial class AddRightResponse : AltInnSrrService.AddRightRequest
    {
        
        private System.Nullable<AltInnSrrService.OperationResult> OperationResultField;
        
        [DataMember()]
        public System.Nullable<AltInnSrrService.OperationResult> OperationResult
        {
            get
            {
                return this.OperationResultField;
            }
            set
            {
                this.OperationResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [DataContract(Name="DeleteRightRequest", Namespace="http://schemas.altinn.no/services/Register/SRR/2015/06")]
    [KnownType(typeof(AltInnSrrService.DeleteRightResponse))]
    public partial class DeleteRightRequest : AltInnSrrService.RegisterSRRRight
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [DataContract(Name="DeleteRightResponse", Namespace="http://schemas.altinn.no/services/Register/SRR/2015/06")]
    public partial class DeleteRightResponse : AltInnSrrService.DeleteRightRequest
    {
        
        private System.Nullable<AltInnSrrService.OperationResult> OperationResultField;
        
        [DataMember()]
        public System.Nullable<AltInnSrrService.OperationResult> OperationResult
        {
            get
            {
                return this.OperationResultField;
            }
            set
            {
                this.OperationResultField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [DataContract(Name="RegisterSRRRightsType", Namespace="http://schemas.altinn.no/services/Register/2015/06")]
    public enum RegisterSRRRightsType : int
    {
        
        [EnumMember()]
        None = 0,
        
        [EnumMember()]
        Read = 1,
        
        [EnumMember()]
        Write = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [DataContract(Name="OperationResult", Namespace="http://schemas.altinn.no/services/Register/2015/06")]
    public enum OperationResult : int
    {
        
        [EnumMember()]
        Unknown = 0,
        
        [EnumMember()]
        Ok = 1,
        
        [EnumMember()]
        RuleNotFound = 2,
        
        [EnumMember()]
        RuleAlreadyExists = 3,
        
        [EnumMember()]
        EmptyOrNotAValidSsnOrOrganisation = 4,
        
        [EnumMember()]
        RightAlreadyExpired = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [CollectionDataContract(Name="AddRightRequestList", Namespace="http://schemas.altinn.no/services/Register/SRR/2015/06", ItemName="AddRightRequest")]
    public class AddRightRequestList : System.Collections.Generic.List<AltInnSrrService.AddRightRequest>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [CollectionDataContract(Name="AddRightResponseList", Namespace="http://schemas.altinn.no/services/Register/SRR/2015/06", ItemName="AddRightResponse")]
    public class AddRightResponseList : System.Collections.Generic.List<AltInnSrrService.AddRightResponse>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [CollectionDataContract(Name="DeleteRightRequestList", Namespace="http://schemas.altinn.no/services/Register/SRR/2015/06", ItemName="DeleteRightRequest")]
    public class DeleteRightRequestList : System.Collections.Generic.List<AltInnSrrService.DeleteRightRequest>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [CollectionDataContract(Name="DeleteRightResponseList", Namespace="http://schemas.altinn.no/services/Register/SRR/2015/06", ItemName="DeleteRightResponse")]
    public class DeleteRightResponseList : System.Collections.Generic.List<AltInnSrrService.DeleteRightResponse>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.altinn.no/services/Register/SRR/2015/06", ConfigurationName="ServiceReference1.IRegisterSRRAgencyExternalBasic")]
    public interface IRegisterSRRAgencyExternalBasic
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AltInnSrrService.AltinnFault), Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        System.Threading.Tasks.Task<AltInnSrrService.TestResponse> TestAsync(AltInnSrrService.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Register/SRR/2015/06/IRegisterSRRAgencyExternalBasi" +
            "c/GetRightsBasic", ReplyAction="http://www.altinn.no/services/Register/SRR/2015/06/IRegisterSRRAgencyExternalBasi" +
            "c/GetRightsBasicResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AltInnSrrService.AltinnFault), Action="http://www.altinn.no/services/Register/SRR/2015/06/IRegisterSRRAgencyExternalBasi" +
            "c/GetRightsBasicAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        System.Threading.Tasks.Task<AltInnSrrService.GetRightsBasicResponse> GetRightsBasicAsync(AltInnSrrService.GetRightsBasicRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Register/SRR/2015/06/IRegisterSRRAgencyExternalBasi" +
            "c/AddRightsBasic", ReplyAction="http://www.altinn.no/services/Register/SRR/2015/06/IRegisterSRRAgencyExternalBasi" +
            "c/AddRightsBasicResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AltInnSrrService.AltinnFault), Action="http://www.altinn.no/services/Register/SRR/2015/06/IRegisterSRRAgencyExternalBasi" +
            "c/AddRightsBasicAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        System.Threading.Tasks.Task<AltInnSrrService.AddRightsBasicResponse> AddRightsBasicAsync(AltInnSrrService.AddRightsBasicRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Register/SRR/2015/06/IRegisterSRRAgencyExternalBasi" +
            "c/DeleteRightsBasic", ReplyAction="http://www.altinn.no/services/Register/SRR/2015/06/IRegisterSRRAgencyExternalBasi" +
            "c/DeleteRightsBasicResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AltInnSrrService.AltinnFault), Action="http://www.altinn.no/services/Register/SRR/2015/06/IRegisterSRRAgencyExternalBasi" +
            "c/DeleteRightsBasicAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        System.Threading.Tasks.Task<AltInnSrrService.DeleteRightsBasicResponse> DeleteRightsBasicAsync(AltInnSrrService.DeleteRightsBasicRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestRequest
    {
        
        public TestRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestResponse
    {
        
        public TestResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRightsBasicRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRightsBasic", Namespace="http://www.altinn.no/services/Register/SRR/2015/06", Order=0)]
        public AltInnSrrService.GetRightsBasicRequestBody Body;
        
        public GetRightsBasicRequest()
        {
        }
        
        public GetRightsBasicRequest(AltInnSrrService.GetRightsBasicRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://www.altinn.no/services/Register/SRR/2015/06")]
    public partial class GetRightsBasicRequestBody
    {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string serviceCode;
        
        [DataMember(Order=3)]
        public int serviceEditionCode;
        
        [DataMember(Order=4)]
        public string reportee;
        
        public GetRightsBasicRequestBody()
        {
        }
        
        public GetRightsBasicRequestBody(string systemUserName, string systemPassword, string serviceCode, int serviceEditionCode, string reportee)
        {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.serviceCode = serviceCode;
            this.serviceEditionCode = serviceEditionCode;
            this.reportee = reportee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRightsBasicResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRightsBasicResponse", Namespace="http://www.altinn.no/services/Register/SRR/2015/06", Order=0)]
        public AltInnSrrService.GetRightsBasicResponseBody Body;
        
        public GetRightsBasicResponse()
        {
        }
        
        public GetRightsBasicResponse(AltInnSrrService.GetRightsBasicResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://www.altinn.no/services/Register/SRR/2015/06")]
    public partial class GetRightsBasicResponseBody
    {
        
        [DataMember(Order=0)]
        public AltInnSrrService.GetRightResponseList GetRightsBasicResult;
        
        public GetRightsBasicResponseBody()
        {
        }
        
        public GetRightsBasicResponseBody(AltInnSrrService.GetRightResponseList GetRightsBasicResult)
        {
            this.GetRightsBasicResult = GetRightsBasicResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRightsBasicRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRightsBasic", Namespace="http://www.altinn.no/services/Register/SRR/2015/06", Order=0)]
        public AltInnSrrService.AddRightsBasicRequestBody Body;
        
        public AddRightsBasicRequest()
        {
        }
        
        public AddRightsBasicRequest(AltInnSrrService.AddRightsBasicRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://www.altinn.no/services/Register/SRR/2015/06")]
    public partial class AddRightsBasicRequestBody
    {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string serviceCode;
        
        [DataMember(Order=3)]
        public int serviceEditionCode;
        
        [DataMember(EmitDefaultValue=false, Order=4)]
        public AltInnSrrService.AddRightRequestList insertRightList;
        
        public AddRightsBasicRequestBody()
        {
        }
        
        public AddRightsBasicRequestBody(string systemUserName, string systemPassword, string serviceCode, int serviceEditionCode, AltInnSrrService.AddRightRequestList insertRightList)
        {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.serviceCode = serviceCode;
            this.serviceEditionCode = serviceEditionCode;
            this.insertRightList = insertRightList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRightsBasicResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRightsBasicResponse", Namespace="http://www.altinn.no/services/Register/SRR/2015/06", Order=0)]
        public AltInnSrrService.AddRightsBasicResponseBody Body;
        
        public AddRightsBasicResponse()
        {
        }
        
        public AddRightsBasicResponse(AltInnSrrService.AddRightsBasicResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://www.altinn.no/services/Register/SRR/2015/06")]
    public partial class AddRightsBasicResponseBody
    {
        
        [DataMember(Order=0)]
        public AltInnSrrService.AddRightResponseList AddRightsBasicResult;
        
        public AddRightsBasicResponseBody()
        {
        }
        
        public AddRightsBasicResponseBody(AltInnSrrService.AddRightResponseList AddRightsBasicResult)
        {
            this.AddRightsBasicResult = AddRightsBasicResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRightsBasicRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteRightsBasic", Namespace="http://www.altinn.no/services/Register/SRR/2015/06", Order=0)]
        public AltInnSrrService.DeleteRightsBasicRequestBody Body;
        
        public DeleteRightsBasicRequest()
        {
        }
        
        public DeleteRightsBasicRequest(AltInnSrrService.DeleteRightsBasicRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://www.altinn.no/services/Register/SRR/2015/06")]
    public partial class DeleteRightsBasicRequestBody
    {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string serviceCode;
        
        [DataMember(Order=3)]
        public int serviceEditionCode;
        
        [DataMember(EmitDefaultValue=false, Order=4)]
        public AltInnSrrService.DeleteRightRequestList deleteRightList;
        
        public DeleteRightsBasicRequestBody()
        {
        }
        
        public DeleteRightsBasicRequestBody(string systemUserName, string systemPassword, string serviceCode, int serviceEditionCode, AltInnSrrService.DeleteRightRequestList deleteRightList)
        {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.serviceCode = serviceCode;
            this.serviceEditionCode = serviceEditionCode;
            this.deleteRightList = deleteRightList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRightsBasicResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteRightsBasicResponse", Namespace="http://www.altinn.no/services/Register/SRR/2015/06", Order=0)]
        public AltInnSrrService.DeleteRightsBasicResponseBody Body;
        
        public DeleteRightsBasicResponse()
        {
        }
        
        public DeleteRightsBasicResponse(AltInnSrrService.DeleteRightsBasicResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://www.altinn.no/services/Register/SRR/2015/06")]
    public partial class DeleteRightsBasicResponseBody
    {
        
        [DataMember(Order=0)]
        public AltInnSrrService.DeleteRightResponseList DeleteRightsBasicResult;
        
        public DeleteRightsBasicResponseBody()
        {
        }
        
        public DeleteRightsBasicResponseBody(AltInnSrrService.DeleteRightResponseList DeleteRightsBasicResult)
        {
            this.DeleteRightsBasicResult = DeleteRightsBasicResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface IRegisterSRRAgencyExternalBasicChannel : AltInnSrrService.IRegisterSRRAgencyExternalBasic, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class RegisterSRRAgencyExternalBasicClient : System.ServiceModel.ClientBase<AltInnSrrService.IRegisterSRRAgencyExternalBasic>, AltInnSrrService.IRegisterSRRAgencyExternalBasic
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RegisterSRRAgencyExternalBasicClient() : 
                base(RegisterSRRAgencyExternalBasicClient.GetDefaultBinding(), RegisterSRRAgencyExternalBasicClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IRegisterSRRAgencyExternalBasic.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RegisterSRRAgencyExternalBasicClient(EndpointConfiguration endpointConfiguration) : 
                base(RegisterSRRAgencyExternalBasicClient.GetBindingForEndpoint(endpointConfiguration), RegisterSRRAgencyExternalBasicClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RegisterSRRAgencyExternalBasicClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RegisterSRRAgencyExternalBasicClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RegisterSRRAgencyExternalBasicClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RegisterSRRAgencyExternalBasicClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RegisterSRRAgencyExternalBasicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AltInnSrrService.TestResponse> AltInnSrrService.IRegisterSRRAgencyExternalBasic.TestAsync(AltInnSrrService.TestRequest request)
        {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<AltInnSrrService.TestResponse> TestAsync()
        {
            AltInnSrrService.TestRequest inValue = new AltInnSrrService.TestRequest();
            return ((AltInnSrrService.IRegisterSRRAgencyExternalBasic)(this)).TestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AltInnSrrService.GetRightsBasicResponse> AltInnSrrService.IRegisterSRRAgencyExternalBasic.GetRightsBasicAsync(AltInnSrrService.GetRightsBasicRequest request)
        {
            return base.Channel.GetRightsBasicAsync(request);
        }
        
        public System.Threading.Tasks.Task<AltInnSrrService.GetRightsBasicResponse> GetRightsBasicAsync(string systemUserName, string systemPassword, string serviceCode, int serviceEditionCode, string reportee)
        {
            AltInnSrrService.GetRightsBasicRequest inValue = new AltInnSrrService.GetRightsBasicRequest();
            inValue.Body = new AltInnSrrService.GetRightsBasicRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.serviceCode = serviceCode;
            inValue.Body.serviceEditionCode = serviceEditionCode;
            inValue.Body.reportee = reportee;
            return ((AltInnSrrService.IRegisterSRRAgencyExternalBasic)(this)).GetRightsBasicAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AltInnSrrService.AddRightsBasicResponse> AltInnSrrService.IRegisterSRRAgencyExternalBasic.AddRightsBasicAsync(AltInnSrrService.AddRightsBasicRequest request)
        {
            return base.Channel.AddRightsBasicAsync(request);
        }
        
        public System.Threading.Tasks.Task<AltInnSrrService.AddRightsBasicResponse> AddRightsBasicAsync(string systemUserName, string systemPassword, string serviceCode, int serviceEditionCode, AltInnSrrService.AddRightRequestList insertRightList)
        {
            AltInnSrrService.AddRightsBasicRequest inValue = new AltInnSrrService.AddRightsBasicRequest();
            inValue.Body = new AltInnSrrService.AddRightsBasicRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.serviceCode = serviceCode;
            inValue.Body.serviceEditionCode = serviceEditionCode;
            inValue.Body.insertRightList = insertRightList;
            return ((AltInnSrrService.IRegisterSRRAgencyExternalBasic)(this)).AddRightsBasicAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AltInnSrrService.DeleteRightsBasicResponse> AltInnSrrService.IRegisterSRRAgencyExternalBasic.DeleteRightsBasicAsync(AltInnSrrService.DeleteRightsBasicRequest request)
        {
            return base.Channel.DeleteRightsBasicAsync(request);
        }
        
        public System.Threading.Tasks.Task<AltInnSrrService.DeleteRightsBasicResponse> DeleteRightsBasicAsync(string systemUserName, string systemPassword, string serviceCode, int serviceEditionCode, AltInnSrrService.DeleteRightRequestList deleteRightList)
        {
            AltInnSrrService.DeleteRightsBasicRequest inValue = new AltInnSrrService.DeleteRightsBasicRequest();
            inValue.Body = new AltInnSrrService.DeleteRightsBasicRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.serviceCode = serviceCode;
            inValue.Body.serviceEditionCode = serviceEditionCode;
            inValue.Body.deleteRightList = deleteRightList;
            return ((AltInnSrrService.IRegisterSRRAgencyExternalBasic)(this)).DeleteRightsBasicAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRegisterSRRAgencyExternalBasic))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRegisterSRRAgencyExternalBasic))
            {
                return new System.ServiceModel.EndpointAddress("http://www.altinn.no/RegisterExternal/RegisterSRRAgencyExternalBasic.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RegisterSRRAgencyExternalBasicClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IRegisterSRRAgencyExternalBasic);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RegisterSRRAgencyExternalBasicClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IRegisterSRRAgencyExternalBasic);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IRegisterSRRAgencyExternalBasic,
        }
    }
}
